name: Publication

on:
  push:
    tags:
      - 'v*'
    branches: [ CI_crate_publication_test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - run: |
          (cd derive && cargo publish --all-features --dry-run)
          cargo publish --all-features --dry-run
